;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Audio.Combat.Swing.Light",DevComment="")
+GameplayTagList=(Tag="HeatAction.Grab.Default",DevComment="Default Heat Action while holding a grabbed target")
+GameplayTagList=(Tag="HeatAction.Normal.Front",DevComment="Standard front-facing Heat Action")

